import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
  Container, Input, Button, FormControl,
  FormLabel,
  FormErrorMessage,
  FormHelperText,
  Stack,
  Text,
  Link,
  Box,
  LinkOverlay,
  LinkBox
} from '@chakra-ui/react'
import { useState } from 'react'




export default function Home() {

  const [url, setUrl] = useState('')
  const [shortUrl, setShortUrl] = useState('')
  const [loading, setLoading] = useState(false)
  const [opacity, setOpacity] = useState(0)

  const submit = async () => {
    //check if url is valid
    if (!url) return
    if (!url.startsWith('https://') && !url.startsWith('http://')) {
      setUrl('https://' + url)
    }
    setLoading(true)

    //call shorten url function
    const res = await fetch('/api/shorten', {
      method: 'POST',
      body: JSON.stringify({
        url: url
      })
  })
  const data = await res.json()
  setShortUrl(`${process.env.NEXT_PUBLIC_API_URL}/id/${data.id}`)
  setLoading(false)
  setOpacity(1)
  }

  return (
    <Box w='100%'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container centerContent maxW={'full'} bgColor={'black'} >
        <LinkBox>
        <LinkOverlay href="https://polybase.xyz">
        <Text  fontSize="md" fontWeight="bold" color={'white'}>Built with Polybase. Click here to learn more. </Text>
        </LinkOverlay>
        </LinkBox>
      </Container>
      <Container maxW='full'  className={styles.main} bgGradient='linear(to-bl, gray.300, purple.300)' centerContent>
        <Stack spacing={50}  w='75%' direction={'column'} >
        <Container maxW={'full'}>
          <Text fontSize="6xl" fontWeight="bold">PolyShort </Text>
          <Text fontSize="xl" fontWeight="bold" color={'gray.100'} >URL shortener built with Polybase</Text>
          </Container>
          <Container >
            <FormControl>
            <FormHelperText fontWeight={'bold'}>Get a shortened link from a decentralized database</FormHelperText>
              <Input type='link' placeholder="Enter your URL here" borderColor={'blackAlpha.300'} value={url} onChange={(e) => setUrl(e.target.value)} />
              <Button onClick={submit} isLoading={loading} colorScheme={'purple'} opacity={'.5'}> Submit</Button>
            </FormControl>
          </Container>
          <Container bgColor={'gray.400'} borderRadius = 'md'  opacity={opacity} >
            <Text fontSize="xl" fontWeight="bold" color = 'HighlightText'>Your shortened link:</Text>
            <Link  href={shortUrl}>{shortUrl}</Link>
          </Container>
        </Stack>
      </Container>
    </Box>
  )
}
