import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
  Container, Input, Button, FormControl,
  FormLabel,
  FormErrorMessage,
  FormHelperText,
  Stack,
  Text,
  Link,
  Box
} from '@chakra-ui/react'
import { useState } from 'react'




export default function Home() {

  const [url, setUrl] = useState('')
  const [shortUrl, setShortUrl] = useState('')
  const [loading, setLoading] = useState(false)
  const [opacity, setOpacity] = useState(0)

  const submit = async () => {
    //check if url is valid
    if (!url) return
    if (!url.startsWith('http')) {
      setUrl('https://' + url)
    }
    setLoading(true)

    //call shorten url function
    const res = await fetch('/api/shorten', {
      method: 'POST',
      body: JSON.stringify({
        url: url
      })
  })
  const data = await res.json()
  setShortUrl(`http://localhost:3000/id/${data.id}`)
  setLoading(false)
  setOpacity(1)
  }

  return (
    <Box w='100%'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW='full'  className={styles.main} bgGradient='linear(to-r, white, purple.300)' centerContent>
        <Stack spacing={10}  w='50%' >
        <Container>
          <Text fontSize="6xl" fontWeight="bold">PolyShort </Text>
          <Text fontSize="xl" fontWeight="bold">URL shortener with a decentralized database</Text>
          </Container>
          <Container>
            <FormControl>
              <Input type='link' placeholder="Enter your URL here" borderColor={'blackAlpha.300'} value={url} onChange={(e) => setUrl(e.target.value)} />
              <FormHelperText>Get a shortened link from a decentralized database</FormHelperText>
              <Button onClick={submit} isLoading={loading}> Submit</Button>
            </FormControl>
          </Container>
          <Container bgColor={'gray.400'} borderRadius = 'md'  opacity={opacity} >
            <Text fontSize="xl" fontWeight="bold" color = 'HighlightText'>Your shortened link:</Text>
            <Link  href={shortUrl}>{shortUrl}</Link>
          </Container>
        </Stack>
      </Container>
    </Box>
  )
}
